baseURL = "http://team-klems.de/"
title = "Team-Klems"

DefaultContentLanguage = "de"

# theme = "hello-friend-ng"
theme = "PaperMod"

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Jörg Klems"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"


  # And you can even create generic menu
  [menu]
#    [[menu.main]]
#      identifier = "impressum"
#      name       = "Impressum"
#      url        = "impressum/"
    [[menu.main]]
      identifier = "blog"
      name       = "Blog"
      url        = "/posts"

    [[menu.footer]]
      identifier = "impressum"
      name       = "Impressum"
      url        = "impressum/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/tiflor"

  [[params.social]]
    name = "email"
    url  = "mailto:webmaster@team-klems.de"

  [[params.social]]
    name = "github"
    url  = "https://github.com/tiflor"
 
[languages]
  [languages.de]
    subtitle  = "Team Klems Blog"
    weight    = 1
    #copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.de.params.logo]
      logoText = "Team Klems :>"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [languages.en]
    # title = "Hello Friend NG"
    subtitle = "Team Klems Blog"
    weight    = 2
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Team Klems :>"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
