baseURL: "https://team-klems.de/"
title: "Team-Klems"
paginate: 5
theme: PaperMod

defaultContentLanguage: de
defaultContentLanguageInSubdir: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45  

params:
  title: Team-Klems
  description: "Team-Klems"
  keywords: [Blog, Portfolio, PaperMod]
  author: "Jörg Klems"
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  label:
      text: "Team-Klems.de"
      # icon: /apple-touch-icon.png
      iconHeight: 35
  # social icons
  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/tiflor"
    - name: "mastodon"
      url: "https://hachyderm.io/@tiflor"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: "github"
      url: "https://github.com/tiflor"
    #- name: "xing"
    #  url: "https://www.xing.de/username/"
    #- name: "linkedin"
    #  url: "https://www.linkedin.com/in/username/"
    - name: "email" 
      url: "mailto:webmaster@team-klems.de"  
    # - name: "medium"
    #   url: ""
    
  # analytics:
  # cSpell:disable
  #     google:
  #         SiteVerificationTag: "XYZabc"
  #     bing:
  #         SiteVerificationTag: "XYZabc"
  #     yandex:
  #         SiteVerificationTag: "XYZabc"
  # cSpell:enable
  editPost:
    URL: "https://github.com/tiflor/team-klems.de/tree/main/content"
    # Text: "Mach einen Änderungsvorschlag" # edit text
    appendFilePath: true # to append file path to Edit link
