de:
  title: team-klems.de
  #contentDir: content/de
  languageName: Deutsch
  weight: 1
  params:
    # home-info mode
    homeInfoParams:
      Title: "Hallo da \U0001F44B"
      Content: Willkommen auf Team-Klems
    # profile-mode
    profileMode:
      enabled: true # needs to be explicitly set
      title: Team Klems
      subtitle: "Willkommen auf Team-Klems \U0001F44B"
      imageUrl: "images/joerg.png"
      imageWidth: 320
      imageHeight: 257
      imageTitle: Bild von Jörg
      buttons:
          - name: Posts
            url: posts
          - name: Categories
            url: categories
  
en:
  title: team-klems.de
  #contentDir: content/en
  languageName: English
  weight: 2
  # home-info mode
  
  params:
    homeInfoParams:
      Title: "Hi there \U0001F44B"
      Content: Welcome to my blog
    # profile-mode
    profileMode:
      enabled: true # needs to be explicitly set
      title: Team Klems
      subtitle: "Welcome to Team-Klems \U0001F44B"
      imageUrl: "images/joerg.png"
      imageWidth: 320
      imageHeight: 257
      imageTitle: Image of Jörg
      buttons:
          - name: Posts
            url: posts
          - name: Categories
            url: categories
