# params:
DateFormat: "January 2, 2006"
defaultTheme: auto # dark, light
disableThemeToggle: false
ShowReadingTime: true
ShowShareButtons: true # share buttons on the bottom of the page
ShareButtons: # share buttons which are displayed
  - twitter
  - linkedin
  #- reddit
  #- facebook
  #- whatsapp
  #- telegram
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: false
disableSpecial1stPost: false
disableScrollToTop: false
comments: false
hidemeta: false
hideSummary: false
showtoc: false
tocopen: false
hideFooter: true # hide default footer and use extended footer

assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    #favicon: "<link / abs url>"
    #favicon16x16: "<link / abs url>"
    #favicon32x32: "<link / abs url>"
    #apple_touch_icon: "<link / abs url>"
    #safari_pinned_tab: "<link / abs url>"

cover:
      hidden: true # hide everywhere but not in structured data
      hiddenInList: true # hide on list pages and home
      hiddenInSingle: true # hide on single page
# for search
# https://fusejs.io/api/options.html
fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai